### ISSUE TITLE
allow to export LDClient, LDFlagSet, LD Options, LDUser interfaces from 'launchdarkly-js-client-sdk'

### ISSUE THREAD

**Issue by glebpigulevsky** [launchdarkly/react-client-sdk#100]
**Is your feature request related to a problem? Please describe.**
I have to install additionally 'launchdarkly-js-client-sdk' to import these interfaces. 

**Describe the solution you'd like**
add the necessary interfaces to index.ts: 
```import LDProvider from './provider';
import withLDProvider from './withLDProvider';
import asyncWithLDProvider from './asyncWithLDProvider';
import withLDConsumer from './withLDConsumer';
import useFlags from './useFlags';
import useLDClient from './useLDClient';
import { camelCaseKeys } from './utils';
import { LDClient, LDFlagSet, LDOptions, LDUser } from 'launchdarkly-js-client-sdk';

export {
  LDProvider,
  withLDProvider,
  withLDConsumer,
  useFlags,
  useLDClient,
  asyncWithLDProvider,
  camelCaseKeys,
  LDClient,
  LDFlagSet,
  LDOptions,
  LDUser,
};
```

**Comment by eli-darkly** [comment]
Are you sure you have to _install_ `launchdarkly-js-client-sdk`? I don't see any reason you wouldn't be able to write this same import in your own code:

```js
import { LDClient, LDFlagSet, LDOptions, LDUser } from 'launchdarkly-js-client-sdk';
```

It sounds like maybe the problem you're having is just that you are trying to do this:
```js
import { LDClient, LDFlagSet, LDOptions, LDUser } from 'launchdarkly-react-client-sdk';
```

**Comment by bwoskow-ld** [comment]
Hi @glebpigulevsky,

We decided against making a code change to resolve this. However, we _did_ improve [our SDK documentation](https://docs.launchdarkly.com/sdk/client-side/react/react-web#importing-types) to clarify how to handle this situation.
