### ISSUE TITLE
Ublock Origin blocks some LaunchDarkly URLs

### ISSUE THREAD

**Issue by ehuange** [launchdarkly/react-client-sdk#153]
Similar to #62, the extension [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en) blocks some requests from LaunchDarkly.

![image](https://user-images.githubusercontent.com/13304704/188236242-6d30eb12-2dfe-42a3-8a56-51aa5210eaa6.png)

**Comment by eli-darkly** [comment]
Thanks for calling our attention to this, but there's no need to file the same issue in multiple repos - https://github.com/launchdarkly/js-client-sdk/issues/255 is literally the same thing, since the React SDK is a wrapper for the JS SDK.
