### ISSUE TITLE
Empty lib/ folder for 2.16.0 release

### ISSUE THREAD

**Issue by klujanrosas** [launchdarkly/react-client-sdk#18]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
`launchdarkly-react-client-sdk@2.16.0` was published with an empty `lib/` folder, causing package managers to report it as a "missing dependency"

**To reproduce**
- Install `launchdarkly-react-client-sdk@2.16.0`
- Try to compile an app importing something from `launchdarkly-react-client-sdk`
- You will get a missing dependency error, because the "main" field is pointing to `lib/index.js`, which *is not there* in the 2.16.0 release

**Expected behavior**
- App compilation succeeds with no errors, and `lib/` folder is populated with compiled sdk code

**Logs**
![image](https://user-images.githubusercontent.com/4474353/70996118-22449e80-20a0-11ea-8a45-a3182b85d67e.png)

**SDK version**
2.16.0

**Language version, developer tools**
Node v10.16.2

**OS/platform**
PopOS 18.01

**Additional context**

**Comment by eli-darkly** [comment]
Hi. Sorry about this! Something went wrong with our last release, and we'll have a new version out ASAP. In the meantime we are unpublishing the 2.16.0 release from npm (which we will only do for a version that's completely broken and unusable, as this is).

**Comment by eli-darkly** [comment]
Released 2.16.1 which should fix this.

**Comment by eli-darkly** [comment]
Apologies again - there was an undetected problem with 2.16.1 (not actually a bug, but a feature that had been enabled before the LD web service was ready to handle it) so it has been superseded by 2.16.2.

**Comment by YUzhva** [comment]
@eli-darkly everything 👌 
Thank you, for a quick fix 💪 

Going to write some code (=
![alt text](https://media3.giphy.com/media/aNqEFrYVnsS52/giphy.gif?cid=790b76116820f8b3ff32b8375a789eeb5c8cb07224e980a4&rid=giphy.gif)
