### ISSUE TITLE
net::ERR_CONNECTION_CLOSED 200 when setting up LaunchDarkly

### ISSUE THREAD

**Issue by paulmbw** [launchdarkly/react-client-sdk#186]
I'm setting up LaunchDarkly in a React project with the [guide](https://app.launchdarkly.com/default/test/get-started/connect-an-sdk). My setup us as follows:
- `launchdarkly-react-client-sdk` version `3.0.3`

index.tsx:
```
const LDProvider = withLDProvider({
  clientSideID: "12345",
  context: {
    kind: "user",
    key: "example_user",
    name: "Paul",
    email: "paul@aster.com",
  },
})(App);


root.render(
  <React.StrictMode>
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <LDProvider />
    </ThemeProvider>
  </React.StrictMode>
);
```

I have a component wrapped with the HOC `withLDConsumer()(Component);` and I'm trying to access `flags` when passed as a prop, but the prop is empty. Upon inspecting the console logs, I'm getting the following errors:

```
GET https://clientstream.launchdarkly.com/eval/<id>/<secret> net::ERR_CONNECTION_CLOSED 200
```

I'm also getting this warning:

```
loggers.js:15 [LaunchDarkly] Error on stream connection: {"isTrusted":true}, will continue retrying after 658 milliseconds.
```

Finally, this is what the dashboard shows unsurprisingly:
<img width="1024" alt="Screenshot 2023-03-12 at 19 45 00" src="https://user-images.githubusercontent.com/9769730/224569223-02a73cea-f549-4c5f-8d3d-c5d1cf4946e0.png">

Where have I gone wrong? Any help would be greatly appreciated!

**Comment by paulmbw** [comment]
Correct! Thanks for the help @codyde much appreciated!

**Comment by louis-launchdarkly** [comment]
Thank you @codyde for your help, and thank you @paulmbw for leaving a note for people who may stumble into this issue in the future.
