### ISSUE TITLE
Declaring an anonymous context doesn't seem possible.

### ISSUE THREAD

**Issue by borisilic-ap** [launchdarkly/react-client-sdk#188]
**Is this a support request?**
No.

**Describe the bug**
With regards to anonymous users there's a mismatch between what the docs say (https://docs.launchdarkly.com/sdk/client-side/javascript/migration-2-to-3#understanding-changes-to-anonymous-users)
> Similarly, in the 3.0 version of the SDK, you can omit the context key when building an anonymous context, and the SDK sets the context key to a generated UUID. 

and what the typescript interfaces enforce: (https://launchdarkly.github.io/js-client-sdk/interfaces/LDContextCommon.html). 

    key
    key: string
    A unique string identifying a context.
    Defined in typings.d.ts:348

According to the docs to enable an anonymous user one would omit the `key` property from the context and set `anonymous: true`. But omitting the `key` property causes TS to complain due to it being required. 

![Screenshot 2023-03-20 at 3 29 42 pm](https://user-images.githubusercontent.com/74516450/226247338-0f159fa0-a731-49d4-87fe-fc2dee94d006.png)

Thoughts? 

**Expected behavior**
Define an anonymous context by being able to omit the `key` property.

**SDK version**
`"launchdarkly-react-client-sdk": "^3.0.0"`

**Language version, developer tools**
React.

**Comment by yusinto** [comment]
[3.0.4 ](https://github.com/launchdarkly/react-client-sdk/releases/tag/3.0.4) has been released and it should fix this issue.

**Comment by borisilic-ap** [comment]
Thank you!

**Comment by borisilic-ap** [comment]
I'm back. I'm a little wary of the solution as it is now. It depends on developers reading the documentation to know to specify the key _unless_ `anonymous` is `true` rather than the behaviour being enforced by typescript. 

Is it possible to implement something along these lines instead: https://stackoverflow.com/a/51412935

**Comment by yusinto** [comment]
Type aliases are great but is not trivial to change our code base right now to do that. Th anonymous and key props are defined in the [common sdk](https://github.com/launchdarkly/js-sdk-common/blob/b61e915089bb39fb36db97c3efe37c296eae8821/typings.d.ts#L340) as an interface which are extended elsewhere. Changing this to be a `type` mean we'll have to re-defined those other interfaces as well. As such, we'll have to stick to the current solution for now and depend on the documentation.
