### ISSUE TITLE
Toggle the killswitch for dev-test-flag in the dashboard but the app does not respond 

### ISSUE THREAD

**Issue by happykayy** [launchdarkly/react-client-sdk#192]
I follow the readme to test the example,
1.In app.js, set clientSideID to your own Client-side ID. You can find this in your LaunchDarkly portal under Account settings / Projects.
2.Create a flag called dev-test-flag in your project. Make sure you make the flag available to the client-side SDK.
3.You should now be able to start the app by doing:
yarn start
4.Toggle the killswitch for dev-test-flag in the dashboard and the app should respond without a browser refresh.

but when I navigate to localhost:3000, in the page it always show "Flag off" no matter the flag is on.
![image](https://user-images.githubusercontent.com/27333951/230585358-1a2494b3-fc44-490e-b883-99eb52a72ff7.png)
![image](https://user-images.githubusercontent.com/27333951/230585425-566035c4-365a-47e2-9a8f-b5aa2c7b003d.png)
please help, thanks!

**Comment by louis-launchdarkly** [comment]
Hello @happykayy, given we need to ask about your account information to help debug this, can you please reach out to us via [LaunchDarkly Support](https://support.launchdarkly.com/hc/en-us/requests/new)?
