### ISSUE TITLE
Version 3.0.5 ships without types

### ISSUE THREAD

**Issue by michaldudek** [launchdarkly/react-client-sdk#197]
**Describe the bug**

I just installed version `3.0.5` and it seems the distributed code is missing TS types, or rather they're not configured properly.

**To reproduce**

- Create a fresh React project.
- `npm install launchdarkly-react-client-sdk`

VSCode tells me:

![Screenshot 2023-04-12 at 20 51 13](https://user-images.githubusercontent.com/802141/231556369-67930bff-dfaf-4aff-9ac4-81841df18acc.png)

Checking the dist code on npm - https://www.npmjs.com/package/launchdarkly-react-client-sdk/v/3.0.5?activeTab=code - it looks like there's now a new folder `/dist` and it only contains `main.js`.

However, `package.json` defines:

```
"types": "dist/index.d.ts",
```

This file does not exist.

**Expected behavior**

TypeScript types should be generated and imported correctly.

**SDK version**
3.0.5

**Language version, developer tools**

- TypeScript 4.9.5
- VSCode 1.77.0
- npm 9.5.0
- node 18.14.2

**OS/platform**

MacOS 13.3.1

**Additional context**

It looks like https://github.com/launchdarkly/react-client-sdk/pull/187 broke this.

For now I downgraded to `3.0.4` and it works fine.

**Comment by yusinto** [comment]
Thanks for reporting this. We are investigating internally and will provide an update soon. Filed internally as 197073.

**Comment by yusinto** [comment]
We have released [3.0.6](https://github.com/launchdarkly/react-client-sdk/releases/tag/3.0.6) which should fix this issue.

**Comment by michaldudek** [comment]
Indeed, it has, thank you :)

**Comment by larsroettig** [comment]
@yusinto rollback is not option why was not invastigated why this dont work ?

**Comment by vladpoltorin** [comment]
hey, I'd like to bump this one again. The type definitions are seem missing in all versions starting from `"launchdarkly-react-client-sdk": "3.0.7"`. I've locked and tested all latest versions - the types are missing.

<img width="642" alt="image" src="https://github.com/launchdarkly/react-client-sdk/assets/15140429/224f13c8-9c67-4027-b1b3-81f9468b5a6e">

  
version `3.0.6` works fine though
