### ISSUE TITLE
Regression in 3.0.7: Attempted import error: 'useFlags' is not exported from 'launchdarkly-react-client-sdk'.

### ISSUE THREAD

**Issue by danwdart** [launchdarkly/react-client-sdk#212]
**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/hc/en-us/requests/new) or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**
With a React app, I can't run yarn build with `import { withFlags, withLDProvider } from "launchdarkly-react-client-sdk";`, can only run yarn dev.

**To reproduce**
With the preceding line in the build, `yarn build` fails with `Attempted import error: 'useFlags' is not exported from 'launchdarkly-react-client-sdk'.` however `yarn dev` works.

**Expected behavior**
The particular functions should be available as soon as they are imported.

**Logs**
`Attempted import error: 'useFlags' is not exported from 'launchdarkly-react-client-sdk'.`

**SDK version**
>= 3.0.7

**Language version, developer tools**
Node 18, yarn

**OS/platform**
Alpine container

**Additional context**
Odd that this seems okay in `yarn dev` but not when optimising code.

**Comment by yusinto** [comment]
Thank you for reporting this. We will investigate. Internally logged as 211138.

**Comment by yusinto** [comment]
@danwdart I am unable to reproduce this issue. The export looks correct in the [npm lib](https://www.npmjs.com/package/launchdarkly-react-client-sdk?activeTab=code) if you see the last line you'll see `useFlags`. Also, we don't have an export called `withFlags` so I believe this maybe your own application's code.

What kind of optimization are you doing to reproduce the issue? Can you please share some more details of the problem: build tools, sample code, and steps to reproduce so we can try and help with this?
