### ISSUE TITLE
Log to console when events aren't sent due to DoNotTrack

### ISSUE THREAD

**Issue by jkjustjoshing** [launchdarkly/react-client-sdk#226]
Update - this is an issue with "Do not track" being enabled. See the following comment for additional context.

**Is your feature request related to a problem? Please describe.**
I just spent 30 minutes trying to figure out why my test application wasn't showing any events. After a lot of digging, it turns out it's due to https://github.com/launchdarkly/react-client-sdk/issues/122. I was fetching flag values with `useFlags()` (which appears to be the preferred way to do it according to the docs), specifying an `application.id` value in the configuration, loading my application, and then trying to figure out why I wasn't seeing the application in https://app.launchdarkly.com/settings/applications (nor any events in the Live Events page).

**Describe the solution you'd like**
Support events using the `useFlags()` hook. The issues described in [this comment](https://github.com/launchdarkly/react-client-sdk/issues/122#issuecomment-1061328715) by @louis-launchdarkly indicate why there isn't a trivial way to support events in that hook. However, with some effort the hook could be updated to work as a new customer would expect:
* When a hook value is accessed, if no other currently-rendered hooks have accessed that value, trigger the event.
* As long as at least 1 hook that has accessed that flag is still rendered, don't trigger another event. Or, just debounce the event by default. Doable by "reference counting" with a `useEffect()` and a counter stored in the context
* When the value is changed on the server and a new value is sent to the client, trigger a single "got the new value" event.

**Describe alternatives you've considered**
Improve the SDK documentation, specifically the `useFlags()` section, to add the disclaimer mentioned in https://github.com/launchdarkly/react-client-sdk/issues/122. This is a huge source of friction as someone new to Launch Darkly and trying to get it set up in my existing application.

**Comment by jkjustjoshing** [comment]
After about 5 hours of debugging, I have realized several things:
* The [2.27.0 release](https://github.com/launchdarkly/react-client-sdk/releases/tag/2.27.0) fixed the issue with `useFlags()`. It now works as expected
* In the websocket payload, I'm getting back `"trackEvents":false` as part of the payload for each flag. I spent quite a bit of time trying to figure out how to turn that "on" in the dashboard or the SDK configuration, since I assumed that's why events weren't logging.
* After an hour of stepping through js-client-sdk code in my debugger, I realized
  * There is another package, js-sdk-common, with much of the business logic of the JS SDK
  * There is a function called [shouldEnqueueEvent()](https://github.com/launchdarkly/js-sdk-common/blob/3473a7c3840351b389eeb0e51fd9205c8ead8072/src/index.js#L133) that was returning `false`
  * There is a function back in js-client-sdk called `isDoNotTrack()` that was returning false
  * I use the Arc browser, which enables "Do not track" by default (though I would have turned it on otherwise).

I was very pleasantly surprised when I realized that LaunchDarkly respects the `navigator.doNotTrack` value. Great job, I approve of this commitment to user consent in tracking.

However, I was equally frustrated that there wasn't an easier way to identify quickly that this is what was happening.

### Request

Can the `isDoNotTrack()` method be updated such that if it returns `true`, it also logs to the console "Launch Darkly events are disabled due to browser Do Not Track settings".

This log would
* Run only once every page load
* Be on by default, but could be turned off by a configuration flag

**Comment by kinyoklion** [comment]
Hello @jkjustjoshing,

Sorry I didn't get to your issue earlier. This is a somewhat confusion that arises when people are using the Arc browser.

Logging it is a little tricky, likely it would need to be an info level log, even if it only happens once per session, the number sessions is really large. 

I think we should incorporate this into documentation someplace.

@mmrj Do you know where would be a good place to put this information?

_Filed internally as 224255_

Thank you,
Ryan

**Comment by kinyoklion** [comment]
For some additional information "trackEvents" is more of a "trackEventsWithGreaterFidelity". This can be used for experimentation or other cases where greater detail is needed for individual flag evaluations.

When that is not set we still summarize events for the individual flags. It just results in less detail and less bandwidth consumption as a result.

**Comment by mmrj** [comment]
> I think we should incorporate this into documentation someplace.
> @mmrj Do you know where would be a good place to put this information?

We should add it to the [Events feature page](https://docs.launchdarkly.com/sdk/features/events). We have a relevant callout at the very end of the [JavaScript section there](https://docs.launchdarkly.com/sdk/features/events#javascript) and should add it to the sections for the other JS-based SDKs. _Filed internally as 224262 for the docs update._
