### ISSUE TITLE
Uncaught XHR Network Errors in Sentry

### ISSUE THREAD

**Issue by NateDawg90** [launchdarkly/react-client-sdk#228]
When using this library with a Sentry configuration, there are sometimes network [errors](https://github.com/launchdarkly/js-client-sdk/issues/283) that occur when the dependency SDK library initializes. These errors come from the underlying `js-client-sdk` library, and should be caught by default by that library.  
![Screenshot 2023-11-27 at 4 18 14 PM](https://github.com/launchdarkly/react-client-sdk/assets/18134083/1a26d246-52ae-492d-a026-927b7d4bbc1d)

Luckily, a recent [fix](https://github.com/launchdarkly/js-client-sdk/releases/tag/3.1.4) to `js-client-sdk` fixes the above issue. The React SDK should simply update its dependency version to ^3.1.4 in order to take advantage of the fix.

**To reproduce**
Observed on my company's deployed application, several hundred uncaught network errors over a span of a week or so.

**Expected behavior**
These errors are caught by the SDK and thus are suppressed from Sentry logs

**SDK version**
3.0.9

**Language version, developer tools**
For instance, Go 1.11 or Ruby 2.5.3. If you are using a language that requires a separate compiler, such as C, please include the name and version of the compiler too.

**OS/platform**
Mac OS

**Comment by yusinto** [comment]
We will fix this and provide an update soon. Filed internally as 226045.

**Comment by NateDawg90** [comment]
Thank you for the fix!
