### ISSUE TITLE
naming typo

### ISSUE THREAD

**Issue by mjesiolowski** [launchdarkly/react-client-sdk#24]
Hey guys,

there is a small typo in `withLDPoviderHoc` function name. "R" is missing in "Provider".

https://github.com/launchdarkly/react-client-sdk/blob/master/src/withLDProvider.tsx#L30

**Comment by bwoskow-ld** [comment]
Thanks for letting us know. We'll get that fixed in an upcoming release.

**Comment by eli-darkly** [comment]
Btw, just to clarify for anyone who sees this issue, this typo had no external consequences— it was in effect just the name of a local variable.

**Comment by eli-darkly** [comment]
Fixed in the 2.17.1 release.
