### ISSUE TITLE
useLDClient returns undefined in version 3.3.0

### ISSUE THREAD

**Issue by Edely** [launchdarkly/react-client-sdk#283]
**Describe the bug**

Have been using LaunchDarkly for a while, but today after upgrading to 3.3.0, useLDClient hook started to return undefined.

This is the code used to initialize the LD context provider:
 

```javascript

 
(async () => { 

  const LDProvider = await asyncWithLDProvider({

    clientSideID: LAUNCHDARKLY_CLIENT_ID,
    context: {
      anonymous: true,
    },
  });


    ReactDOM.render(
      <React.StrictMode>
      <LDProvider>
          <App />
      </LDProvider>
    </React.StrictMode>,
    document.getElementById("root")
  );

})();

```

 

Later in the application, I get the client in the following way:

 

```javascript
const ldClient = useLDClient();
useEffect(() => {
    ldClient.waitForInitialization().then(() => {
        ldClient.identify({ kind: "user", key: USER_EMAIL });
    });
}, []);

```        

**Expected behavior**
useLDClient should return the LD client.

**SDK version**
3.3.0

**OS/platform**
Chrome 125.0.6422.76 (Official Build) (arm64)  / MacOs Sonoma 14

**Comment by alonfixler** [comment]
I experience it as well. Worked fine for version 3.2.0.

**Comment by zeratulmdq** [comment]
I thought I was loosing my mind 😂 Same here, 3.0.10 used to work fine, 3.3.0 is failing for me.

**Comment by Pod-2-Ji-Woong-You** [comment]
Been using 3.0.10, and it just stopped working since 3 days ago. When I try to build the app through GitHub Action, I run into a following error.
```
#18 79.46 ERROR in ./node_modules/launchdarkly-react-client-sdk/lib/cjs/index.js 35:22
#18 79.46 Module parse failed: Unexpected token (35:22)
#18 79.46 File was processed with these loaders:
#18 79.46  * ./node_modules/babel-loader/lib/index.js
#18 79.46 You may need an additional loader to handle the result of these loaders.
#18 79.46 |     Consumer: l
#18 79.46 |   } = a,
#18 79.46 >   u = e => e.context ?? e.user,
#18 79.46 |   p = e => {
#18 79.46 |     const t = {};
#18 79.46  @ ./src/LDProvider.js 3:0-63 20:15-29
```

Here's the `./src/LDProvider.js`
```javascript
import React from 'react';
import PropTypes from 'prop-types';
import { withLDProvider } from 'launchdarkly-react-client-sdk';
import { LD_CLIENT_ID } from './environment';

function LDProvider(props) {
  return <div>{props.children}</div>;
}

LDProvider.propTypes = {
  children: PropTypes.object,
};

const context = {
  kind: 'user',
  key: 'practice-anonymous',
};

export default withLDProvider({
  clientSideID: LD_CLIENT_ID,
  context,
})(LDProvider);

```

**Comment by yusinto** [comment]
Thank you for reporting this. We are investigating and will provide an update soon. Internally logged as 245619.

**Comment by Pod-2-Ji-Woong-You** [comment]
@yusinto I appreciate your prompt response to this matter

**Comment by Pod-2-Ji-Woong-You** [comment]
@yusinto hello our build is started failing now with `3.3.2`. Could you please advise?

**Comment by kinyoklion** [comment]
Hello @Pod-2-Ji-Woong-You You can pin your js-client-sdk, or update your webpack version. The underlying issue here is that the js-client-sdk generates code with `?.` in it, and webpack versions more than approximately 4 years old don't understand the syntax without the addition of babel. If you already have babel you may able able to adjust your configuration. The version of js-client-sdk isn't pinned by the SDK, so it floated to the new version. If you have a webpack version greater than 5.0.0, please let me know and we can attempt to narrow why it would be having this problem.

Thank you,
Ryan
