### ISSUE TITLE
Show some examples of your product being used with react static site generators

### ISSUE THREAD

**Issue by Blumed** [launchdarkly/react-client-sdk#3]
**Is your feature request related to a problem? Please describe.**
We are trying to get your SDK to work with Gatsby's ssr and browser api's and the way your api and Gatsby api is laid out it is really challenging to get working.

**Describe the solution you'd like**
It might be nice to have some examples using your api with other popular api's.

**Describe alternatives you've considered**
Maybe point to some Gists that show common implementations would be nice or maybe even a blog post would suffice. Especially since LaunchDarkly.com is a Gatsby site :)

**Additional context**
That is all.

**Comment by bwoskow-ld** [comment]
Hi @Blumed,

Take a look at the ["Example App"](https://docs.launchdarkly.com/docs/react-sdk-reference#section-example-app) section of our SDK reference guide. While the sample isn't a Gatsby app, it should be enough to get you going.

Let us know if there's anything else you need from us! If you have further questions about issues with the SDK then you can reply on this issue tracker. Alternatively if you have questions about how to use the SDK then it would be best to contact our support team at support@launchdarkly.com.
