### ISSUE TITLE
How to set values on the fly?

### ISSUE THREAD

**Issue by janhesters** [launchdarkly/react-client-sdk#32]
When the user logs in, I want to change the user values from `anonymous` to the user's values. I couldn't find anything in the docs on how to do this.

How would you change the values of the config after the SDK has been initialized?

**Comment by bwoskow-ld** [comment]
Hi @janhesters,

As mentioned in [our React SDK documentation](https://docs.launchdarkly.com/sdk/client-side/react#users), all user-related functionality provided by the JavaScript SDK is equally accessible in the React SDK. All you need to do is grab the `ldClient` as described on that page.

For your particular question, you'll want to first [construct a user object](https://docs.launchdarkly.com/sdk/client-side/javascript#users) and then [call `identify`](https://docs.launchdarkly.com/sdk/client-side/javascript#changing-the-user-context) with it.

If you have any further questions about using the SDK, feel free to reach out to our support team at support@launchdarkly.com.

Cheers,
Ben
