### ISSUE TITLE
initialization errors aren't always surfaced

### ISSUE THREAD

**Issue by eli-darkly** [launchdarkly/react-client-sdk#4]
This issue was originally filed by @martinmckenna when the React SDK code was still part of the [js-client-sdk](https://github.com/launchdarkly/js-client-sdk) repository. The original issue description and discussion is [here](https://github.com/launchdarkly/js-client-sdk/issues/175).

Summary: in the specific case where an environment ID was not provided, the underlying JS SDK will fail to initialize but this type of failure is not communicated to the React SDK, so it will hang.

The original issue also mentioned the possibility of an existing environment ID becoming invalid so that LD would return a 401 or 403 error. We believe that in this case the React SDK _will_ notice the error, but we should verify that.

**Comment by eli-darkly** [comment]
[tracked internally as 55120]

**Comment by Lukortech** [comment]
Any updates on this issue?

**Comment by XieX** [comment]
@Lukortech @Jshollow A solution for this went out in [2.27.0](https://github.com/launchdarkly/react-client-sdk/releases/tag/2.27.0), take a look and see if it suits your needs. We added a new hook that will surface initialization failures, read [useLDClientError](https://launchdarkly.github.io/react-client-sdk/index.html#useLDClientError).

**Comment by Lukortech** [comment]
> @Lukortech @Jshollow A solution for this went out in [2.27.0](https://github.com/launchdarkly/react-client-sdk/releases/tag/2.27.0), take a look and see if it suits your needs. We added a new hook that will surface initialization failures, read [useLDClientError](https://launchdarkly.github.io/react-client-sdk/index.html#useLDClientError).

Thanks for the mention, I am not a part of active team working with use of this sdk but I will try to see if It's good now.

**Comment by lucasmendesdeliver** [comment]
@XieX I could not see any references on how to use useLDClientError
