### ISSUE TITLE
Overriding Feature Flag Manually

### ISSUE THREAD

**Issue by mustafashabib** [launchdarkly/react-client-sdk#53]
**Is your feature request related to a problem? Please describe.**
I'd love to know how to manually override a feature flag using the useFlags hook to force certain variations for testing (headless browser for example) purposes

**Describe the solution you'd like**
Set a localStorage var or cookie and have the LD react client bias to using those values before checking with the LD service.

**Describe alternatives you've considered**
Creating our own useFlags hook that wraps the LD hook but which has this behavior.

**Comment by bwoskow-ld** [comment]
Hi @mustafashabib ,

Are you using jest? If so check out https://github.com/launchdarkly-labs/jest-launchdarkly-mock to manually set flag values in your tests.

**Comment by mustafashabib** [comment]
Thanks @bwoskow-ld - that's definitely useful. We were thinking of how we might test this for cypress end to end tests (or even to manually override just for dev purposes while we're working through a new feature to force a specific variant).

Thanks

**Comment by bwoskow-ld** [comment]
Is the jest-launchdarkly-mock library sufficient for your testing use case? Let me know if there's anything else or if I can close this ticket.

As for overriding values for development, our best practice is to have a unique LaunchDarkly environment per developer on your team. This way, each developer can use the LaunchDarkly UI to manage flags for their local environment without impacting any other developers or environments.

**Comment by bwoskow-ld** [comment]
@mustafashabib I'm going to close this issue now. Let me know if there's anything else on the topic you want to add.

**Comment by nweajoseph** [comment]
> Is the jest-launchdarkly-mock library sufficient for your testing use case? Let me know if there's anything else or if I can close this ticket.
> 
> As for overriding values for development, our best practice is to have a unique LaunchDarkly environment per developer on your team. This way, each developer can use the LaunchDarkly UI to manage flags for their local environment without impacting any other developers or environments.

this sounds cool, but in my workplace we have limited licenses. only 3 people have access to launchdarkly as users, so there's no way for all of use to use a unique environment that we can use to toggle flags arbitrarily during development. for us, some way to manually define the flag values would be ideal:

```tsx
const ldProviderConfig: ProviderConfig = {
  clientSideID: process.env.LD_CLIENT_ID || '',
  user: ldAnonUser,
  options: {
    flags: {
      'flag-being-developed': true // this flag will always resolve to true in this client
      'flag-not-being-developed': false // this flag will always resolve to false in this client
    }
  },
}
const LDProvider = withLDProvider(ldProviderConfig)(App)
```

or something like that

**Comment by nweajoseph** [comment]
i originally tried to write my own context provider / wrapper that offered consumers some predefined static flag values and left the others alone, but i don't see anyway to hook into `withLDProvider` that really allows that strategy

**Comment by mustafashabib** [comment]
~~~typescript
import type { LDFlagSet } from 'launchdarkly-js-sdk-common';
import { useFlags as useLDFlags } from 'launchdarkly-react-client-sdk';
import { useState } from 'react';

const useFlags = (): LDFlagSet => {
    const getManualOverrides = (): LDFlagSet => {
        try {
            return JSON.parse(localStorage.getItem('override-flags') || '{}');
        } catch {
            return {};
        }
    };

    const [overrides, setOverrides] = useState(getManualOverrides());

    window.onstorage = (): void => {
        setOverrides(getManualOverrides());
    };

    const ldFlags = useLDFlags();

    if (ENABLE_LAUNCHDARKLY) {
        const mergedFlags = { ...ldFlags, ...(overrides as LDFlagSet) } as LDFlagSet;
        return mergedFlags;
    } else return overrides as LDFlagSet;
};

export default useFlags;

~~~

**Comment by nweajoseph** [comment]
@mustafashabib oh i see that makes sense. you merge the static flag values _after_ fetching the real ones.

**Comment by biggytech** [comment]
Would be ideal if we could to add some manual set flags into `ProviderConfig`. It is very handy for local development, for example.

**Comment by kellyrmilligan** [comment]
I think this should be re-opened. for larger teams, it is really nice to locally be able to toggle things off and on regardless of which env you're pointed to. would be nice to have something like react-query's dev tools to add flags manually and do a merge of sorts.

**Comment by kellyrmilligan** [comment]
as fyi, my company added something similar to the above as well, but suited to our own needs. There is definitely a need for this IMO.

**Comment by kevinfiol** [comment]
Surprising this feature is not included as part of the SDK. Thanks all for posting your solutions.

**Comment by Radivarig** [comment]
@bwoskow-ld please reopen

**Comment by bwoskow-ld** [comment]
Hi all - there are a few related-yet-different requests going on on this thread at the moment.

As I mentioned a several years (!) ago, it's possible to use the jest library if you want to override values in jest tests. This remains possible today.

Much more recently, we shifted our solution towards enabling developers to [override values from the LaunchDarkly CLI](https://docs.launchdarkly.com/guides/flags/ldcli-dev-server). With the help of our CLI, you can spin up a lightweight LaunchDarkly development server and then point your SDK to it while overriding whatever flag values you need. You could run this development server anywhere that the CLI supports e.g. locally or in CI. **This is our recommended solution.**

Lastly, regarding the earlier comments about being seat-restricted and as a result not being able to have one LaunchDarkly environment per developer - LaunchDarkly's [pricing plans](https://launchdarkly.com/pricing/) now have unlimited seats. If you're on a legacy pricing plan with limited seats, speak with your account owner about switching to a newer pricing plan.

**Comment by bwoskow-ld** [comment]
And after all that, if you still feel like you're looking for something different - please create a new issue. We don't actively monitor closed issues and a new issue would be much more effective at getting our team's attention. Thanks!
