### ISSUE TITLE
XHR error on GET /sdk/evalx/[REDACTED]/users/[REDACTED]

### ISSUE THREAD

**Issue by salterj** [launchdarkly/react-client-sdk#57]
**Describe the bug**
We are occasionally seeing the following error in our React app:
```
XHR error GET https://app.launchdarkly.com/sdk/evalx/[REDACTED]/users/[REDACTED]
Failed to load
```
For context, we initialize the SDK with the `withLDProvider` function.

**To reproduce**
Unclear

**Expected behavior**
The error does not occur.

**Logs**
The error snippet above is the only relevant log.

**SDK version**
`2.20.2`

**Language version, developer tools**
React `16.13.1`
Typescript `4.1.3

**OS/platform**
Windows 10, Chrome `87.0.4280.88`
Mac OS `10.15.7`, Chrome `87.0.4280.141`, `88.0.4324.96`

**Additional context**
The only other similar issue I've been able to find is with the Javascript client https://github.com/launchdarkly/js-client-sdk/issues/126, but I am unsure if it is the same problem.

**Comment by bwoskow-ld** [comment]
Hi @salterj ,

I have to redirect you to our support team at support@launchdarkly.com. There you'll be able to safely discuss the issue without needing to redact any information. The support team is well equipped to handle this issue and will escalate to the engineering team as needed.

Cheers,
@bwoskow-ld

**Comment by salterj** [comment]
Thanks @bwoskow-ld, I chose to open an issue because I didn't think the actual IDs that I redacted are important to the underlying cause. But no worries, will redirect to your support team. Thanks!

**Comment by bwoskow-ld** [comment]
Understood.

The second redacted value very well might be important -- that is based on the user you're trying to identify. If your user is invalid then the LaunchDarkly REST API will return an error; this may or may not be your problem here. You'll be able to safely describe your user object structure with our support team.
