### ISSUE TITLE
Access flags without provider

### ISSUE THREAD

**Issue by grug** [launchdarkly/react-client-sdk#74]
Hi there - this might be a silly question, but is it possible to access flags without needing hooks? I need to access flags at a point in my application before the React application is actually instantiated (it's to control whether or not to register a service worker). Any help is appreciated :)

**Comment by ctawiah** [comment]
Hi @grug, I believe you can use our [javascript client sdk](https://github.com/launchdarkly/js-client-sdk) to achieve this, you can read the documentation [here](https://docs.launchdarkly.com/sdk/client-side/javascript#section-getting-started). Our `react-client-sdk` actually uses the `launchdarkly-js-client-sdk` under the hood. For your use case, you can explore the example approach below:

```javascript
import * as LDClient from 'launchdarkly-js-client-sdk';

const ldclient = LDClient.initialize('YOUR_CLIENT_SIDE_ID', { anonymous: true });

const renderApp = () => (
  ReactDOM.render(
    <React.StrictMode>
      <App />
    </React.StrictMode>,
    document.getElementById('root')
  )
)

ldclient.on('ready', () => {
  const registerWorker = ldclient.variation("YOUR_FEATURE_KEY", false);
  
  if (registerWorker) {
    // init worker
  } else {
    renderApp();
  }
});

ldclient.on('change', function(flags) {
  console.log('flags changed:', flags);
  // add your feature behavior here...
});
```

Hope this helps.

**Comment by grug** [comment]
Hey @ctawiah I'll give this a go today and let you know how it goes :) I really appreciate you responding to me!

**Comment by ctawiah** [comment]
Hi @grug, i'm going to close this ticket for now, please re-open it or create a new one if you run into any additional issues. Thanks.
